services:
  postgres:
    image: postgres:16-alpine
    container_name: crud_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: crud_secret
      POSTGRES_DB: crud_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

